name: CI Comment Triggered Integration Test with Publishing

on:
  issue_comment:
    types: [ created ]

permissions:
  contents: read

jobs:
  PR_comment:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER
        env:
          NUMBER: ${{ github.event.issue.number }}

  PRC_w_check_name:
    if: ${{ github.event.issue.pull_request && (github.actor.login == 'hypotrochoid' || github.actor.login == 'winston-bosan') }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER w check for name
        env:
          NUMBER: ${{ github.event.issue.number }}

  PRc_check_name_and_content:
    if: ${{ github.event.issue.pull_request && (github.actor.login == 'hypotrochoid' || github.actor.login == 'winston-bosan') && contains(github.event.comment.body, 'integrationNOW') }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo A comment on PR $NUMBER w check for name and content
        env:
          NUMBER: ${{ github.event.issue.number }}
