name: Manual Dispatch Based CI Comment Triggered Integration Test with Publishing

on:
  workflow_dispatch:
    inputs:
      issueNumber:
        description: 'Ditto'
        required: false
        default: ''
        type: string

permissions:
  contents: read

jobs:
  dispatch_base:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.extract_pr_branch_name.outputs.git_branch }}
    steps:
      - id: extract_pr_branch_name
        run: |
          echo ${{ github.event }}
          echo ${{ github.ref }}
          echo A comment on PR $NUMBER w check for name and content
          echo "I am PR#:${{ github.event.issue.number }}"
          echo "running on branch ${GITHUB_REF##*/}"
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "git_branch=$GIT_BRANCH" >> "$GITHUB_OUTPUT"
          echo "$GIT_BRANCH"

  printOut:
    runs-on: ubuntu-latest
    needs: dispatch_base
    steps:
      - env:
          OUTPUT1: ${{needs.dispatch_base.outputs.branch_name}}
        run: echo "$OUTPUT1"
      - run: |
          echo "$GIT_BRANCH"