name: Dispatch Based CI Comment Triggered Integration Test with Publishing

on:
  workflow_dispatch:
    inputs:
      issueNumber:
        description: 'Ditto'
        required: false
        default: ''
        type: string
      SHA:
        description: 'SHA of the commit you want to run integration on (defaults to which branch u call it from)'
        required: false
        default: ''
        type: string

permissions:
  contents: read

jobs:
  dispatch_base:
    runs-on: ubuntu-latest
    outputs:
      pr_num: ${{ steps.extract_pr_num.outputs.pr_num || inputs.issueNumber }}
    steps:
      - id: extract_pr_num
        run: |
          echo ${{ github.event }}
          echo ${{ github.ref }}
          echo A comment on PR $NUMBER w check for name and content
          echo "I am PR#:${{ github.event.issue.number }}"
          echo "running on branch ${GITHUB_REF##*/}"
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
          echo "$GIT_BRANCH"
          
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "$PR_NUMBER"
          echo "pr_num=$PR_NUMBER" >> "$GITHUB_OUTPUT"
        env:
          NUMBER: ${{ github.ref || github.event.issue.number }}
          GIT_BRANCH: ${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}

  extract_sha_pr_name_to_output:
    needs: [ dispatch_base ]
    runs-on: ubuntu-latest
    outputs:
      branchName: ${{ steps.api.outputs.branchName }}
      headSHA: ${{ steps.api.outputs.headSHA }}
    steps:
      - id: api
        run: |
          tempHeadRefName=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/winston-bosan/isolation/pulls/${{ needs.dispatch_base.outputs.pr_num }}" | jq .head.ref )
          
          tempHeadRefSHA=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/winston-bosan/isolation/pulls/${{ needs.dispatch_base.outputs.pr_num }}" | jq .head.sha )
          
          echo $tempHeadRefName
          echo $tempHeadRefSHA
          
          echo "branchName=$tempHeadRefName" >> "$GITHUB_OUTPUT"
          echo "headSHA=$tempHeadRefSHA" >> "$GITHUB_OUTPUT"

  printOut:
    runs-on: ubuntu-latest
    needs: extract_sha_pr_name_to_output
    steps:
      - env:
          OUTPUT1: ${{needs.extract_sha_pr_name_to_output.outputs.branchName}}
          OUTPUT2: ${{needs.extract_sha_pr_name_to_output.outputs.headSHA}}
        run: echo "$OUTPUT1 $OUTPUT2"